CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"role" INTEGER,
	"phone" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	"full_name" VARCHAR(255),
	"login" VARCHAR(255) NOT NULL CHECK(LENGTH(login) > 3),
	"date_create" TIMESTAMP NOT NULL,
	"date_update" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);


CREATE UNIQUE INDEX "users_index_id"
ON "users" ("id");

CREATE TABLE IF NOT EXISTS "orders" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"capacity" INTEGER NOT NULL,
	"lifting_capacity" INTEGER NOT NULL,
	"type" INTEGER,
	"manager_id" INTEGER,
	"status" INTEGER NOT NULL DEFAULT 1,
	"price" DECIMAL,
	"pickup_address" VARCHAR(255),
	"delivery_address" VARCHAR(255),
	"date_start" DATE,
	"date_end" DATE,
	"period_from" DATE,
	"period_to" DATE,
	"date_create" TIMESTAMP NOT NULL,
	"date_update" TIMESTAMP,
	PRIMARY KEY("id")
);


CREATE INDEX "orders_index_status"
ON "orders" ("status");
CREATE INDEX "orders_index_1"
ON "orders" ("user_id", "manager_id", "capacity", "lifting_capacity", "status");

CREATE TABLE IF NOT EXISTS "driver" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL UNIQUE,
	"status" INTEGER NOT NULL DEFAULT 0,
	"date_create" TIMESTAMP NOT NULL,
	"date_update" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "driver_index_status"
ON "driver" ("status");
CREATE INDEX "driver_index_1"
ON "driver" ("user_id");

CREATE TABLE IF NOT EXISTS "auto" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"status" INTEGER NOT NULL DEFAULT 0,
	"capacity" INTEGER NOT NULL,
	"lifting_capacity" INTEGER NOT NULL,
	"number" VARCHAR(10) NOT NULL,
	"required_category" VARCHAR(10) NOT NULL,
	"date_create" TIMESTAMP,
	"date_update" TIMESTAMP,
	PRIMARY KEY("id")
);


CREATE INDEX "auto_index_capacity"
ON "auto" ("capacity");
CREATE INDEX "auto_index_lifting_capacity"
ON "auto" ("lifting_capacity");
CREATE INDEX "auto_index_2"
ON "auto" ("status");
CREATE INDEX "auto_index_3"
ON "auto" ("required_category");

CREATE TABLE IF NOT EXISTS "driver_auto" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"driver_id" INTEGER,
	"order_id" INTEGER,
	"auto_id" INTEGER,
	"status" INTEGER NOT NULL DEFAULT 0,
	"date_finish" DATE,
	"date_create" TIMESTAMP,
	"date_update" TIMESTAMP,
	PRIMARY KEY("id")
);


CREATE INDEX "driver_auto_index_0"
ON "driver_auto" ("driver_id");
CREATE INDEX "driver_auto_index_1"
ON "driver_auto" ("order_id");
CREATE INDEX "driver_auto_index_2"
ON "driver_auto" ("auto_id");

CREATE TABLE IF NOT EXISTS "driver_category" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"driver_id" INTEGER NOT NULL,
	"category" VARCHAR(10) NOT NULL,
	"date_create" TIMESTAMP NOT NULL,
	"date_update" TIMESTAMP,
	PRIMARY KEY("id")
);


CREATE INDEX "driver_category_index_0"
ON "driver_category" ("category");
CREATE INDEX "driver_category_index_1"
ON "driver_category" ("driver_id");

CREATE TABLE IF NOT EXISTS "managers" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"status" INTEGER,
	"date_create" TIMESTAMP NOT NULL,
	"date_update" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "managers_index_status"
ON "managers" ("status");
CREATE INDEX "managers_index_1"
ON "managers" ("user_id");
ALTER TABLE "managers"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "driver"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "driver_auto"
ADD FOREIGN KEY("driver_id") REFERENCES "driver"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "driver_auto"
ADD FOREIGN KEY("auto_id") REFERENCES "auto"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "driver_auto"
ADD FOREIGN KEY("order_id") REFERENCES "orders"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "driver_category"
ADD FOREIGN KEY("driver_id") REFERENCES "driver"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "orders"
ADD FOREIGN KEY("manager_id") REFERENCES "managers"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;