version: "3.8"

services:
    db:
        image: postgres:14
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=freightmanagementdb
            - POSTGRES_USER=admin
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
            - ./init-scripts:/docker-entrypoint-initdb.d
        networks:
            - backend
    
    user-app:
        build: ./user-service
        depends_on:
            - db
        networks:
            - backend
        env_file:
            - .env
        ports:
            - "8080:8080"
    resource-app:
        build: ./resource-service
        depends_on:
            - db
        networks:
            - backend
        env_file:
            - .env
        ports:
            - "8080:8080"        
networks:
    backend: