// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: user-service/proto/userpb/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_service_proto_userpb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_userpb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_userpb_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_user_service_proto_userpb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_userpb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_userpb_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_service_proto_userpb_user_proto protoreflect.FileDescriptor

const file_user_service_proto_userpb_user_proto_rawDesc = "" +
	"\n" +
	"$user-service/proto/userpb/user.proto\x12\x04user\"#\n" +
	"\x11CreateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"+\n" +
	"\x0fCreateUserReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2D\n" +
	"\x04User\x12<\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x15.user.CreateUserReplyB\x1bZ\x19user-service/proto/userpbb\x06proto3"

var (
	file_user_service_proto_userpb_user_proto_rawDescOnce sync.Once
	file_user_service_proto_userpb_user_proto_rawDescData []byte
)

func file_user_service_proto_userpb_user_proto_rawDescGZIP() []byte {
	file_user_service_proto_userpb_user_proto_rawDescOnce.Do(func() {
		file_user_service_proto_userpb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_userpb_user_proto_rawDesc), len(file_user_service_proto_userpb_user_proto_rawDesc)))
	})
	return file_user_service_proto_userpb_user_proto_rawDescData
}

var file_user_service_proto_userpb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_service_proto_userpb_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil), // 0: user.CreateUserRequest
	(*CreateUserReply)(nil),   // 1: user.CreateUserReply
}
var file_user_service_proto_userpb_user_proto_depIdxs = []int32{
	0, // 0: user.User.CreateUser:input_type -> user.CreateUserRequest
	1, // 1: user.User.CreateUser:output_type -> user.CreateUserReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_proto_userpb_user_proto_init() }
func file_user_service_proto_userpb_user_proto_init() {
	if File_user_service_proto_userpb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_userpb_user_proto_rawDesc), len(file_user_service_proto_userpb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_userpb_user_proto_goTypes,
		DependencyIndexes: file_user_service_proto_userpb_user_proto_depIdxs,
		MessageInfos:      file_user_service_proto_userpb_user_proto_msgTypes,
	}.Build()
	File_user_service_proto_userpb_user_proto = out.File
	file_user_service_proto_userpb_user_proto_goTypes = nil
	file_user_service_proto_userpb_user_proto_depIdxs = nil
}
